# Site settings
title: Yeat... another tech blog
description: A blog about Technology... Yeahh!!!
baseurl: "/ulisses-telemaco" # the subpath of your site, e.g. /blog
url: "https://utelemaco.github.io" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Ulisses Telemaco
user_description: Father of two girls, husband.. in spare time, I'm a passionated developer
user_title: Ulisses Telemaco
email: ulisses.telemaco@gmail.com
twitter_username: utelemaco
github_username:  utelemaco
gplus_username:  lorem_ipsum
disqus_username: lorem_ipsum

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:title/


# html minify
compress_html:
  clippings: all
  comments: all
  endings: []
  profile: false

# Links to include in menu navigation
# For external links add external: true
links:
  - title: Home
    url: /
  - title: Series
    url: /series
  - title: Tags
    url: /tags
  - title: About Me
    url: /about

# exclude my node related stuff
exclude: ['package.json', 'src', 'node_modules']
